name: Update submodules

# Controls when the action will run. 

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: snickerbockers/submodules-init@v4
    - uses: ./
      with:
        milliseconds: 1000
